### PR TITLE
fix: solana mechanism for return has changed yet again

### PR DESCRIPTION
**Pull request by vbstreetz**
unless am wrong:

```
[
  'Program 3vtWFA1tozq1mfZAMJfAVtQVvRkTjeio8rkyRFzRuTP5 invoke [1]',
  'Program 3vtWFA1tozq1mfZAMJfAVtQVvRkTjeio8rkyRFzRuTP5 consumed 1020 of 200000 compute units',
  'Program return: 3vtWFA1tozq1mfZAMJfAVtQVvRkTjeio8rkyRFzRuTP5 CMN5oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNEbyB0aGUgcmV2ZXJ0IHRoaW5nAAAAAAAAAAAAAAAAAA==',
  'Program 3vtWFA1tozq1mfZAMJfAVtQVvRkTjeio8rkyRFzRuTP5 failed: custom program error: 0x0'
]
```

tested on latest `solanalabs/solana:edge` image.

### CODE REVIEW

**Comment by vbstreetz** [comment]
yeap https://github.com/solana-labs/solana/commit/d714cf659cc2190e62cfe1ff733327bb0ca6e6ae#diff-e750277a1cdee4e5d4de5fdd18f498e1edf553210324252c4e85ba3a2da4b842

**Comment by seanyoung** [comment]
See https://wiki.hyperledger.org/display/TSC/DCO+Validation+During+Contribution+Review

**Review by seanyoung — CHANGES_REQUESTED** [review]
Please add DCO

**Comment by seanyoung** [comment]
Thank you!

**Pull request merged**
