### PR TITLE
feat(parser): support revert statement

### LINKED ISSUE #696: custom error reverts unsupported by solang-parser
Stumbled upon this when looking at this for example https://github.com/withtally/rollcall/blob/main/src/Executor.sol 

which solang-parser fails to parse at the parentheses 

https://github.com/withtally/rollcall/blob/6ffdcffc41ba163a83a93f1b03c97815b6e49fa4/src/Executor.sol#L28

I couldn't find where "revert" is implemented so would need some pointers where to modify lalrpop rules for this before I can try fixing this

### PR DESCRIPTION
**Pull request by mattsse**
Closes #696

Followed these instructions https://github.com/hyperledger-labs/solang/issues/696#issuecomment-1066666159

revert statement remains `unimplemented!` in `sema`

### CODE REVIEW

**Comment by seanyoung** [comment]
My suggested parser changes did not work. I'm trying to see what changes are needed, let me get back to you

**Comment by seanyoung** [comment]
@mattsse I don't think I can add commits to your PR, but here is a commit which fixes the grammar: https://github.com/seanyoung/solang/commit/16ee98629f67c94adfab6ba5970832f65f3d415c

**Comment by mattsse** [comment]
Thanks so much!
https://github.com/seanyoung/solang/commit/16ee98629f67c94adfab6ba5970832f65f3d415c appended

**Comment by seanyoung** [comment]
There is also an issue in the solang-parser test, I had not tested that, this should fix that https://github.com/seanyoung/solang/commit/787515bf9d3f4d1a3f5fed3d863f6e784a00f932

**Comment by seanyoung** [comment]
The vscode extension needs a small fix for the test to pass, in vscode/src/test/suite/extension.test.ts

**Review by seanyoung — APPROVED** [review]

**Comment by seanyoung** [comment]
Looks great, I'll fixup the vscode test in a follow up PR

**Pull request merged**
