### PR TITLE
More info for overload

### PR DESCRIPTION
**Pull request by guanqun**
fix https://github.com/hyperledger-labs/solang/issues/707

### CODE REVIEW

**Comment by guanqun** [comment]
question: how to add a unit test for UI?

**Review by seanyoung — CHANGES_REQUESTED** [review]
That error message looks great! :1st_place_medal: My first observation is the same change needs to be repeated for method calls, method calls with named arguments, constructor calls, constructor calls with named arguments. 

> question: how to add a unit test for UI?

I think the best way to add test cases for this is to do the following:
- Add some solidity files with bad overloaded calls to the `tests/contract_tests/solana/` directory.
- Re-generate the test data by uncommenting these three lines: https://github.com/hyperledger-labs/solang/blob/main/tests/contract.rs#L80-L82
- Run `cargo test --test contract` 
- Putting comments back on the three lines https://github.com/hyperledger-labs/solang/blob/main/tests/contract.rs#L80-L82
- Inspect the newly created dot files. Do they have the correct error message in them with the notes?

**Comment by guanqun** [comment]
Thanks for the comments. Will add the overloaded info for other cases.

**Comment by guanqun** [comment]
Sorry I don't have enough time on this. Closing this PR.

**Pull request closed without merging**
