### PR TITLE
Update seal debug message

### PR DESCRIPTION
**Pull request by xermicus**
The `seal_println` runtime function was superseded by `seal_debug_message` in Substrate v3.0. This PR makes the `print("...")` builtin work again for current Substrate versions.

### CODE REVIEW

**Review by seanyoung — CHANGES_REQUESTED** [review]
This looks good, but I have a few concerns.

- Commits in hyperledger must have the `Signed-off-by: real name <email@address>` line at the end of each commit.
- We have a mock substrate VM which is very useful for debugging and for tests. This mock substrate should be updated too (see `tests/substrate.rs`).
- There are tests against the mock substrate which should pass, for example https://github.com/hyperledger-labs/solang/blob/main/tests/substrate_tests/strings.rs#L596-L612
- We have tests against real substrate 3.0 which will fail now. Updating them to the latest substrate will cause many problems.
- How is this tested against latest substrate? Can we automate this somehow (this might be hard to do right now).

**Comment by seanyoung** [comment]
Some of the Solidity files in `integration/substrate/*.sol` contain `print(..);` lines. There aren't actually used as part of the test; you could comment them out for now, and the substrate tests will probably pass then.

The vscode test failure is unrelated to your changes. I'm fixing it here: https://github.com/hyperledger-labs/solang/pull/913

**Comment by xermicus** [comment]
> Some of the Solidity files in `integration/substrate/*.sol` contain `print(..);` lines. There aren't actually used as part of the test; you could comment them out for now, and the substrate tests will probably pass then.

Thank you Sean! I probably will do just that. The plan is to update everything to the latest substrate version, once this PR is merged. Also, there won't be any more breaking changes in the future (on the substrate side), which should mean newer versions should always work. What we could then do is adding compiler flags for new features, for example (how to proceed here is another discussing for another day, first we just want to update everything to the latest version).

> The vscode test failure is unrelated to your changes. I'm fixing it here: #913

Perfect, I'll backport it when your're done, thanks!

**Comment by xermicus** [comment]
@athei please check this as well

**Review by athei — APPROVED** [review]
LGTM

Good follow up would be to call this function from `assert_failure` so we get those `require` messages printed.

**Comment by xermicus** [comment]
> Good follow up would be to call this function from `assert_failure` so we get those `require` messages printed.

Agree, I'll open an issue for that

**Pull request merged**
