### PR TITLE
Make solidity parser a standalone crate

### PR DESCRIPTION
**Pull request by mattsse**
This is essentially a followup on #597 and makes the solidity parser a standalone crate (`solang-parser`)

## Changes
* move `src/parser/*` to `solang-parser`, including lalrpop build
* move `src/sema/ast/Diagnostic` related structs to `solang-parser/src/diagnostics/`. This was necessary because the parser's error is the Diagnostic, but has the downside that some `Diagnostic` implementation is now in two places:
  * made `src/sema/ast/Diagnostic::formatted_message` a function that accepts a `&Diagnostic` instead
* rm unused dependencies in solang 
* reexport the parser, so it doesn't break

### CODE REVIEW

**Review by gakonst — APPROVED** [review]
lgtm

**Comment by seanyoung** [comment]
Good idea. Just reviewing now.

**Review by seanyoung — APPROVED** [review]
LGTM

**Comment by seanyoung** [comment]
I've uploaded https://crates.io/crates/solang-parser

**Comment by mattsse** [comment]
Amazing, thank you!

**Pull request merged**
