### PR TITLE
Load stdlib only once

### LINKED ISSUE #807: LLVM Crashes when building contract
The following contract crashes LLVM, when building for target ewasm.

```solidity
/**
 *Submitted for verification at Etherscan.io on 2022-03-14
*/

//SPDX-License-Identifier: Unlicensed

pragma  solidity  ^0.8.5;
abstract  contract  Context  {
        function  _msgSender()  internal  view  virtual  returns  (address  payable)  {
                return  payable(msg.sender);
        }
        function  _msgData()  internal  view  virtual  returns  (bytes  memory)  {
                this;
                return  msg.data;
        }
}

contract  Ownable  is  Context  {
        address  private  _owner;
      
        event  OwnershipTransferred(address  indexed  previousOwner,  address  indexed  newOwner);
        constructor  ()  {
                address  msgSender  =  _msgSender();
                _owner  =  msgSender;
                emit  OwnershipTransferred(address(0),  msgSender);
        }
        function  owner()  public  view  returns  (address)  {
                return  _owner;
        }

        modifier  onlyOwner()  {
                require(_owner  ==  _msgSender(),  "Ownable:  caller  is  not  the  owner");
                _;
        }

        function  waiveOwnership()  public  virtual  onlyOwner  {
                emit  OwnershipTransferred(_owner,  address(0));
                _owner  =  address(0);
        }

        function  transferOwnership(address  newOwner)  public  virtual  onlyOwner  {
                require(newOwner  !=  address(0),  "Ownable:  new  owner  is  the  zero  address");
                emit  OwnershipTransferred(_owner,  newOwner);
                _owner  =  newOwner;
        }
        
        function  getTime()  public  view  returns  (uint256)  {
                return  block.timestamp;
        }
}

```

The error is the following:
```
llvm-project/llvm/lib/IR/Instructions.cpp:1480: void llvm::StoreInst::AssertOK(): Assertion `cast<PointerType>(getOperand(1)->getType()) ->isOpaqueOrPointeeTypeMatches(getOperand(0)->getType()) && "Ptr must be a pointer to Val type!"' failed.
```

### PR DESCRIPTION
**Pull request by LucasSte**
This PR fixes #807. We are now only loading the stdlib module only once and linking it against any other modules we create. Although LLVM types are global, I believe LLVM adds a `.0` to the end of the type name for disambiguation, because it does not check if two types of equal names represent the same structure in the memory. In this sense, whenever we load stdlib again, LLVM understands that is a totally new module and tries to disambiguate type names.

Please, @seanyoung check if I did not remove any necessary pointer cast.

### CODE REVIEW

**Review by seanyoung — CHANGES_REQUESTED** [review]
Looks good, however I found one pointer_cast() which can now be removed, I think.
binary.rs:926

**Comment by seanyoung** [comment]
The burrow test is failing because of https://www.npmjs.com/package/solc/v/0.8.14 is broken (I think).

**Comment by LucasSte** [comment]
> Looks good, however I found one pointer_cast() which can now be removed, I think. binary.rs:926

Thanks for catching that. I've removed that cast too.

**Comment by LucasSte** [comment]
> The burrow test is failing because of https://www.npmjs.com/package/solc/v/0.8.14 is broken (I think).

A fix has already been released: https://www.npmjs.com/package/solc

**Review by seanyoung — APPROVED** [review]

**Pull request merged**
