### PR TITLE
Disable eliminating unused variables when optimization level is None (-O none)

### PR DESCRIPTION
**Pull request by taquangtrung**
Hi,

I created this new PR to fix all problems mentioned in the previous PR https://github.com/hyperledger-labs/solang/pull/560

I also fixed the problems mentioned by @LucasSte in https://github.com/hyperledger-labs/solang/pull/560#issuecomment-967294935

Can you help to review it?

Thanks!

### CODE REVIEW

**Comment by seanyoung** [comment]
@taquangtrung thanks for your PR. The CI tests must pass, so please run `cargo fmt` on your code, and make sure your commit signed with `Signed-off-by: Real Name <email@address>`.

**Comment by taquangtrung** [comment]
@seanyoung: I updated the PR as suggested! Hopefully this time the CI will not throw any error.

**Comment by taquangtrung** [comment]
@seanyoung: it seems that the build for Solana failed CI test. 

Can you advise how can I run this test locally?

**Comment by seanyoung** [comment]
That failure is nothing to do with any changes you made, not to worry. I think it looks good.

**Comment by seanyoung** [comment]
That solana test should really check for a range of values, rather than one specific value.

**Review by seanyoung — APPROVED** [review]

**Pull request merged**
