### PR TITLE
docs: optimize keywords

### PR DESCRIPTION
**Pull request by ctjlewis**
This is the 5th Google result for "solidity solana," and I think it should be the 1st one (amazing project)—the docs actually rank 3 places higher.

My main goal was just to include the word "Solana" in the `h1`, but I added the other targets for good measure. It's a little wordy, but I think it is worth merging (even if after a little tinkering).

### CODE REVIEW

**Comment by seanyoung** [comment]
Thanks for fixing that -- this was totally missed.

Hyperledger requires a DCO. Please can you add a `Signed-off-by: real-name <email-address>` to your commit, thank you.

**Comment by ctjlewis** [comment]
All good, beat me by 10 seconds @seanyoung!

**Comment by ctjlewis** [comment]
Tests passed now, thanks you for such a quick review @seanyoung, and incredible work you guys are doing on this project!

**Comment by bertho-zero** [comment]
There is the same description on [github](https://github.com/hyperledger-labs/solang)

image

**Comment by ctjlewis** [comment]
Good work Sean, looks great!

**Pull request merged**
