### PR TITLE
Remove double call to expression in destructure codegen

### PR DESCRIPTION
**Pull request by LucasSte**
This PR is a quick fix for calling `expression` twice when doing code generation for restructure statements.
Instead of calling `expression`, I call `storage_load` to create the `LoadStorage` instruction in the CFG.

### CODE REVIEW

**Review by seanyoung — APPROVED** [review]
The change works, but it's just as ugly as the original (albeit less broken).

**Comment by LucasSte** [comment]
> The change works, but it's just as ugly as the original (albeit less broken).

Do you have any ideas on possible changes that are less ugly?

**Comment by seanyoung** [comment]
> > The change works, but it's just as ugly as the original (albeit less broken).
> 
> Do you have any ideas on possible changes that are less ugly?

I've been thinking about this and nothing has come to mind. Do you think that your new version of `fn cast()` for codegen could deal with this?

**Comment by LucasSte** [comment]
> > > The change works, but it's just as ugly as the original (albeit less broken).
> > 
> > 
> > Do you have any ideas on possible changes that are less ugly?
> 
> I've been thinking about this and nothing has come to mind. Do you think that your new version of `fn cast()` for codegen could deal with this?

My new version of Cast works basically the same way the old one, expect that now it is a method of `cfg::Expression`. If I were to solve the `LoadStorage` issue within `cast`, `cfg` should be passed as an argument to cast. I do believe that `cast` should be self-contained, in a way that it does not depend on the CFG.

**Comment by seanyoung** [comment]
The same issue exists for `return foo()` on line https://github.com/hyperledger-labs/solang/blob/5da5377b6fce0d1aec98fa58041a4126540a226d/src/codegen/statements.rs#L842-L843

**Comment by seanyoung** [comment]
I think we should have:
- Separate this functionality out into a function with a big fat comment explaining why it is needed (cast not done in sema)
- Reuse this function for all three cases.

**Pull request closed without merging**
